# Generated by Django 5.2.3 on 2025-09-29 17:03

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Post = apps.get_model('post', 'Post')
    Comment = apps.get_model('post', 'Comment')
    
    # Populate Post slugs
    for post in Post.objects.filter(slug__isnull=True):
        base_slug = slugify(post.title) if post.title else 'post'
        if not base_slug:
            base_slug = 'post'
        
        post.slug = base_slug
        original_slug = post.slug
        counter = 1
        while Post.objects.filter(slug=post.slug).exclude(pk=post.pk).exists():
            post.slug = f"{original_slug}-{counter}"
            counter += 1
        post.save()
    
    # Populate Comment slugs
    for comment in Comment.objects.filter(slug__isnull=True):
        import time
        timestamp = comment.created_at.strftime('%Y%m%d%H%M%S') if comment.created_at else time.strftime('%Y%m%d%H%M%S')
        post_title = slugify(comment.post.title) if comment.post and comment.post.title else 'post'
        username = slugify(comment.user.username) if comment.user and comment.user.username else 'user'
        
        base_slug = f"{username}-{post_title}-{timestamp}"
        comment.slug = slugify(base_slug)
        
        original_slug = comment.slug
        counter = 1
        while Comment.objects.filter(slug=comment.slug).exclude(pk=comment.pk).exists():
            comment.slug = f"{original_slug}-{counter}"
            counter += 1
        comment.save()


def reverse_populate_slugs(apps, schema_editor):
    # No need to reverse this operation
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_comment_slug_alter_post_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
